### ISSUE TITLE
自编译的luci-app-unblockmusic v1.3-2不能运行

### ISSUE THREAD

**Issue by ydch** [project-openwrt/luci-app-unblockmusic#1]
用LEAN的LEDE源码编译，不能运行，但下载的发行版luci-app-unblockmusic v1.3-2在LEDE固件上安装后可以运行。

**Comment by 1715173329** [comment]
如遇无法运行问题，请尝试手动执行init中相关命令，排查错误。
建议：
1. 检查是否是因为luci错误操作init导致，可手动运行 `service unblockmusic restart` 查看是否运行
2. 检查是否是因为nodejs相关问题导致，可手动运行 `node -v` 检查是否正确编译node
3. 尝试手动运行程序 `node /usr/share/unblockmusic/app.js -p $(uci get unblockmusic.@unblockmusic[0].port) -s`，检查是否出现错误
4. 如一切无误，且无法找到发生原因，可手动更改init文件查看效果

**Comment by ydch** [comment]
感谢回复！还是node的问题。将node编译进固件运行出错，但单独安装没问题。

**Comment by 1715173329** [comment]
请手动检查依赖是否勾全，源码有无错误等
